### ISSUE TITLE
Issue updating home phone on Gentoo

### ISSUE THREAD

**Issue by Kangie** [bluesabre/mugshot#10]
Mugshot (0.4.2) does not save when I enter data into the 'Home Phone' field. I receive the following error: 
> An error occurred while saving changes
> User details were not updated.

The error appears after asking me to escalate privileges, which seems to work just fine 

I've run mugshot in debug mode, and receive the following output (sanitised):
>DEBUG:mugshot: process_terminal_password() 'Executing: /usr/bin/chfn -h "[phone number]" [username]'
>DEBUG:mugshot: save_chfn_details() 'Updating Office Phone...'
>DEBUG:mugshot: process_terminal_password() 'Executing: /usr/bin/chfn -p "none" [username]'
>DEBUG:mugshot: process_terminal_password() 'Executing: /usr/bin/chfn -w "none" [username]'

No error appears in the console. 

I can see that mugshot supports both versions of chfn (shadow-utils and util-linux), so I doubt that's the issue. I can manually set the home phone using chfn -h "[phone number] [username]" and it works successfully and can be read by mugshot on next startup.

**Comment by lucenera** [comment]
Thanks for your workaround. But I see that after a year there is still no response. I have the same problem on Void Linux.

**Comment by Saijin-Naib** [comment]
Fixed it for me in Alpine Linux as well, thank you
