### ISSUE TITLE
mugshot - not working

### ISSUE THREAD

**Issue by visious25** [bluesabre/mugshot#22]
Hi, I got this error in terminal:

$ mugshot
Traceback (most recent call last):
  File "/usr/bin/mugshot", line 35, in <module>
    import mugshot
ModuleNotFoundError: No module named 'mugshot'

PS: I'm currently using arch linux.

**Comment by bluesabre** [comment]
How did you install Mugshot? AUR? From source? Something else?

**Comment by visious25** [comment]
Your right, I just installed Mugshot from AUR and it's working. I had Mugshot from different source.

**Comment by bluesabre** [comment]
Thanks for letting me know. Closing this one out.

**Comment by visious25** [comment]
No problem you're welcome.
