### ISSUE TITLE
The mugshot package has been removed from the GNU/Debian 10 (Buster) repositories

### ISSUE THREAD

**Issue by tomassenabre** [bluesabre/mugshot#6]
Hello,
The mugshot package has been removed from the GNU/Debian Buster repositories, but the XFCE whiskermenu plugin needs this package to edit the user's profile. Whiskermenu issues an error because it does not find mugshot installed in the system.
Thanks for your job
Tomas

**Comment by tux93** [comment]
I don't think @bluesabre can do much about this, you might want to get into contact with the Debian packagers instead

**Comment by bluesabre** [comment]
This is correct. Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932867#12 for more information. Closing this issue.
