### ISSUE TITLE
Gentoo installation instructions

### ISSUE THREAD

**Issue by Kangie** [bluesabre/mugshot#9]
Unable to make a pull request for wiki pages (who knew?), so, Gentoo installation instructions:

emerge --sync
emerge x11-misc/mugshot

There's a few use flags as well, that can be added to /etc/portage/package.use to enable various features; 

libreoffice - libreoffice integration
webcam - assuming that it enables webcam capture support
gnome - gnome integration?

**Comment by bluesabre** [comment]
Thanks for the addition. Included on the [wiki](https://github.com/bluesabre/mugshot/wiki/Installation).
